queue: Hosted VS2017

trigger:
- master

steps:
  - task: NuGetToolInstaller@0
    displayName: "Install nuget.exe and add to PATH"
    inputs:
        versionSpec: 4.8.*

  - powershell: |
        $patUser = 'prestopa@microsoft.com'
        $patToken = 'osxbfvv6l33stbgrfesykrzbyf6y5q46aw7qroiljpyywh5lxfwq'
        $securePat = ConvertTo-SecureString -String $patToken -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential($patUser, $securePat)
        $vsGalleryUrl = 'https://pkgs.dev.azure.com/autocloudarc/_packaging/VSGallery/nuget/v3/index.json'
        $vsRepsitoryName = "VSGallery"
        $moduleName = 'WriteToLogs'

        Register-PSRepository -Name $vsRepsitoryName -SourceLocation $vsGalleryUrl -PublishLocation $vsGalleryUrl -InstallationPolicy Trusted -Credential $credential -Verbose

        nuget.exe sources add -name $vsRepsitoryName -Source $vsGalleryUrl -UserName $patUser -Password $patToken

        Publish-Module -Path ".\$env:BUILD_REPOSITORY_NAME\$moduleName" -Repository $vsRepsitoryName -Credential $credential -NuGetApiKey $vsRepsitoryName -Verbose

    displayName: "Publish PowerShell module"
    failOnStderr: true